title: "Matías Gil – Senior Software Engineer"
description: "2025 – Built with ❤️ and Markdown"
theme: minima
stylesheet: "/assets/css/styles.css"
author: "Matias Gil-Echavarría"
github_username: matiasdim

